package com.platon.browser.dao.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;

public class NodeHistoryTotalAndStatDelegateValue extends NodeHistoryTotalAndStatDelegateValueKey {
    private BigDecimal statDelegateValueMax;

    private BigDecimal statDelegateValueMin;

    private BigDecimal statDelegateValueAvg;

    private BigDecimal statDelegateValueTotal;

    private Integer statDelegateValueCount;

    private BigDecimal statStakingValueMax;

    private BigDecimal statStakingValueMin;

    private BigDecimal statStakingValueAvg;

    private BigDecimal statStakingValueTotal;

    private Integer statStakingValueCount;

    private Date createTime;

    private Date updateTime;

    public BigDecimal getStatDelegateValueMax() {
        return statDelegateValueMax;
    }

    public void setStatDelegateValueMax(BigDecimal statDelegateValueMax) {
        this.statDelegateValueMax = statDelegateValueMax;
    }

    public BigDecimal getStatDelegateValueMin() {
        return statDelegateValueMin;
    }

    public void setStatDelegateValueMin(BigDecimal statDelegateValueMin) {
        this.statDelegateValueMin = statDelegateValueMin;
    }

    public BigDecimal getStatDelegateValueAvg() {
        return statDelegateValueAvg;
    }

    public void setStatDelegateValueAvg(BigDecimal statDelegateValueAvg) {
        this.statDelegateValueAvg = statDelegateValueAvg;
    }

    public BigDecimal getStatDelegateValueTotal() {
        return statDelegateValueTotal;
    }

    public void setStatDelegateValueTotal(BigDecimal statDelegateValueTotal) {
        this.statDelegateValueTotal = statDelegateValueTotal;
    }

    public Integer getStatDelegateValueCount() {
        return statDelegateValueCount;
    }

    public void setStatDelegateValueCount(Integer statDelegateValueCount) {
        this.statDelegateValueCount = statDelegateValueCount;
    }

    public BigDecimal getStatStakingValueMax() {
        return statStakingValueMax;
    }

    public void setStatStakingValueMax(BigDecimal statStakingValueMax) {
        this.statStakingValueMax = statStakingValueMax;
    }

    public BigDecimal getStatStakingValueMin() {
        return statStakingValueMin;
    }

    public void setStatStakingValueMin(BigDecimal statStakingValueMin) {
        this.statStakingValueMin = statStakingValueMin;
    }

    public BigDecimal getStatStakingValueAvg() {
        return statStakingValueAvg;
    }

    public void setStatStakingValueAvg(BigDecimal statStakingValueAvg) {
        this.statStakingValueAvg = statStakingValueAvg;
    }

    public BigDecimal getStatStakingValueTotal() {
        return statStakingValueTotal;
    }

    public void setStatStakingValueTotal(BigDecimal statStakingValueTotal) {
        this.statStakingValueTotal = statStakingValueTotal;
    }

    public Integer getStatStakingValueCount() {
        return statStakingValueCount;
    }

    public void setStatStakingValueCount(Integer statStakingValueCount) {
        this.statStakingValueCount = statStakingValueCount;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table node_history_total_and_stat_delegate_value
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        nodeId("node_id", "nodeId", "VARCHAR", false),
        date("date", "date", "TIMESTAMP", true),
        statDelegateValueMax("stat_delegate_value_max", "statDelegateValueMax", "DECIMAL", false),
        statDelegateValueMin("stat_delegate_value_min", "statDelegateValueMin", "DECIMAL", false),
        statDelegateValueAvg("stat_delegate_value_avg", "statDelegateValueAvg", "DECIMAL", false),
        statDelegateValueTotal("stat_delegate_value_total", "statDelegateValueTotal", "DECIMAL", false),
        statDelegateValueCount("stat_delegate_value_count", "statDelegateValueCount", "INTEGER", false),
        statStakingValueMax("stat_staking_value_max", "statStakingValueMax", "DECIMAL", false),
        statStakingValueMin("stat_staking_value_min", "statStakingValueMin", "DECIMAL", false),
        statStakingValueAvg("stat_staking_value_avg", "statStakingValueAvg", "DECIMAL", false),
        statStakingValueTotal("stat_staking_value_total", "statStakingValueTotal", "DECIMAL", false),
        statStakingValueCount("stat_staking_value_count", "statStakingValueCount", "INTEGER", false),
        createTime("create_time", "createTime", "TIMESTAMP", false),
        updateTime("update_time", "updateTime", "TIMESTAMP", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table node_history_total_and_stat_delegate_value
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table node_history_total_and_stat_delegate_value
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table node_history_total_and_stat_delegate_value
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table node_history_total_and_stat_delegate_value
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table node_history_total_and_stat_delegate_value
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table node_history_total_and_stat_delegate_value
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table node_history_total_and_stat_delegate_value
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table node_history_total_and_stat_delegate_value
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table node_history_total_and_stat_delegate_value
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table node_history_total_and_stat_delegate_value
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table node_history_total_and_stat_delegate_value
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table node_history_total_and_stat_delegate_value
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table node_history_total_and_stat_delegate_value
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table node_history_total_and_stat_delegate_value
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table node_history_total_and_stat_delegate_value
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }
    }
}