package com.platon.browser.dao.mapper;

import com.github.pagehelper.Page;
import com.platon.browser.dao.entity.DelegationLog;
import com.platon.browser.dao.entity.DelegationLogExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface DelegationLogMapper {
    long countByExample(DelegationLogExample example);

    int deleteByExample(DelegationLogExample example);

    int deleteByPrimaryKey(Long id);

    int insert(DelegationLog record);

    int insertSelective(DelegationLog record);

    Page<DelegationLog> selectByExample(DelegationLogExample example);

    DelegationLog selectByPrimaryKey(Long id);

    int updateByExampleSelective(@Param("record") DelegationLog record, @Param("example") DelegationLogExample example);

    int updateByExample(@Param("record") DelegationLog record, @Param("example") DelegationLogExample example);

    int updateByPrimaryKeySelective(DelegationLog record);

    int updateByPrimaryKey(DelegationLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delegation_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<DelegationLog> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delegation_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<DelegationLog> list, @Param("selective") DelegationLog.Column ... selective);
}