package com.platon.browser.dao.mapper;

import com.platon.browser.dao.entity.NodeHistoryTotalAndStatDelegateValue;
import com.platon.browser.dao.entity.NodeHistoryTotalAndStatDelegateValueExample;
import com.platon.browser.dao.entity.NodeHistoryTotalAndStatDelegateValueKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NodeHistoryTotalAndStatDelegateValueMapper {
    long countByExample(NodeHistoryTotalAndStatDelegateValueExample example);

    int deleteByExample(NodeHistoryTotalAndStatDelegateValueExample example);

    int deleteByPrimaryKey(NodeHistoryTotalAndStatDelegateValueKey key);

    int insert(NodeHistoryTotalAndStatDelegateValue record);

    int insertSelective(NodeHistoryTotalAndStatDelegateValue record);

    List<NodeHistoryTotalAndStatDelegateValue> selectByExample(NodeHistoryTotalAndStatDelegateValueExample example);

    NodeHistoryTotalAndStatDelegateValue selectByPrimaryKey(NodeHistoryTotalAndStatDelegateValueKey key);

    int updateByExampleSelective(@Param("record") NodeHistoryTotalAndStatDelegateValue record, @Param("example") NodeHistoryTotalAndStatDelegateValueExample example);

    int updateByExample(@Param("record") NodeHistoryTotalAndStatDelegateValue record, @Param("example") NodeHistoryTotalAndStatDelegateValueExample example);

    int updateByPrimaryKeySelective(NodeHistoryTotalAndStatDelegateValue record);

    int updateByPrimaryKey(NodeHistoryTotalAndStatDelegateValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table node_history_total_and_stat_delegate_value
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<NodeHistoryTotalAndStatDelegateValue> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table node_history_total_and_stat_delegate_value
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<NodeHistoryTotalAndStatDelegateValue> list, @Param("selective") NodeHistoryTotalAndStatDelegateValue.Column ... selective);
}