package com.platon.browser.dao.mapper;

import com.platon.browser.dao.entity.NodeHistoryDeleAnnualizedRate;
import com.platon.browser.dao.entity.NodeHistoryDeleAnnualizedRateExample;
import com.platon.browser.dao.entity.NodeHistoryDeleAnnualizedRateKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NodeHistoryDeleAnnualizedRateMapper {
    long countByExample(NodeHistoryDeleAnnualizedRateExample example);

    int deleteByExample(NodeHistoryDeleAnnualizedRateExample example);

    int deleteByPrimaryKey(NodeHistoryDeleAnnualizedRateKey key);

    int insert(NodeHistoryDeleAnnualizedRate record);

    int insertSelective(NodeHistoryDeleAnnualizedRate record);

    List<NodeHistoryDeleAnnualizedRate> selectByExample(NodeHistoryDeleAnnualizedRateExample example);

    NodeHistoryDeleAnnualizedRate selectByPrimaryKey(NodeHistoryDeleAnnualizedRateKey key);

    int updateByExampleSelective(@Param("record") NodeHistoryDeleAnnualizedRate record, @Param("example") NodeHistoryDeleAnnualizedRateExample example);

    int updateByExample(@Param("record") NodeHistoryDeleAnnualizedRate record, @Param("example") NodeHistoryDeleAnnualizedRateExample example);

    int updateByPrimaryKeySelective(NodeHistoryDeleAnnualizedRate record);

    int updateByPrimaryKey(NodeHistoryDeleAnnualizedRate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table node_history_dele_annualized_rate
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<NodeHistoryDeleAnnualizedRate> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table node_history_dele_annualized_rate
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<NodeHistoryDeleAnnualizedRate> list, @Param("selective") NodeHistoryDeleAnnualizedRate.Column ... selective);
}